spring:
  application:
    name: store

stripe:
  apiUrl: https://api.stripe.com
  timeout: 1000
  enabled: true
  support-currency: USD,EUR,GBP

payment-gateway: paypal
mail:
  host: http://smtp.gmail.com
  port: 5671